import { create } from "zustand";
import { 
  Node, 
  Edge, 
  Connection, 
  addEdge, 
  OnNodesChange, 
  OnEdgesChange,
  OnConnect,
  applyNodeChanges,
  applyEdgeChanges
} from "@xyflow/react";
import { v4 as uuidv4 } from "uuid";
import { getCodeForNodeType } from "@/lib/codeTemplates";

export type NodeData = {
  label: string;
  type: string;
  config: Record<string, unknown>;
};

interface GraphState {
  nodes: Node<NodeData>[];
  edges: Edge[];
  selectedNode: string | null;
  
  addNode: (type: string, position: { x: number; y: number }, config?: Record<string, unknown>, options?: { selectNode?: boolean }) => void;
  addNodesWithEdges: (nodes: Array<{ type: string; position: { x: number; y: number }; config?: Record<string, unknown> }>, edges?: Array<{ source: number; target: number }>) => void;
  addOutputNode: () => void;
  updateNodeConfig: (nodeId: string, config: Record<string, unknown>) => void;
  updateNodeType: (nodeId: string, type: string, config?: Record<string, unknown>) => void;
  deleteNode: (nodeId: string) => void;
  selectNode: (nodeId: string | null) => void;
  clearAll: () => void;
  loadDefaultWorkflow: () => void;
  
  onNodesChange: OnNodesChange<Node<NodeData>>;
  onEdgesChange: OnEdgesChange<Edge>;
  onConnect: OnConnect;
  addEdge: (edge: Edge) => void;
}

export const nodeDefaults: Record<string, Partial<NodeData>> = {
  pipeline: {
    label: "Pipeline",
    config: {
      pipelineId: "",
      pipelineName: "",
      remoteInference: false,
    },
  },
  videoInput: {
    label: "Video Input",
    config: {},
  },
  textPrompt: {
    label: "Text Prompt",
    config: { text: "", weight: 1.0 },
  },
  imageInput: {
    label: "Image Input",
    config: { path: "" },
  },
  parameters: {
    label: "Parameters",
    config: {},
  },
  custom: {
    label: "Custom Processor",
    config: { 
      name: "My Processor",
      params: [],
      code: "",
      isCodeMode: true,
    },
  },
  pipelineOutput: {
    label: "Pipeline Output",
    config: { usage: "main" },
  },
  pluginConfig: {
    label: "Plugin Configuration",
    config: {
      pipelineId: "",
      pipelineName: "My Plugin",
      pipelineDescription: "Generated by OpenScope",
      usage: "main",
      mode: "video",
      supportsPrompts: true,
      remoteInference: false,
    },
  },
  noteGuide: {
    label: "Note",
    config: {
      title: "Step 1",
      content: "1. Add instructions here.\n2. Edit in the properties panel.",
    },
  },
  lessonGettingStarted: {
    label: "Getting Started",
    config: {
      title: "1. Getting Started",
      content: `Welcome to OpenScope! 

OpenScope is a visual plugin builder for Daydream Scope that lets you create AI video processing pipelines without coding.

KEY CONCEPTS:
• Plugin Config - Defines your plugin's identity (name, ID, usage type)
• Inputs - Video, Text Prompts, or Image References  
• Pipelines - AI models fetched from Scope server
• Preprocessors - Modify input before main pipeline
• Postprocessors - Modify output after main pipeline

GETTING STARTED:
1. Create a Plugin Config node first
2. Choose your usage type (main/preprocessor/postprocessor)
3. Add input nodes based on your mode
4. Connect nodes by dragging from output to input handles
5. Toggle the code icon to see the Python code!

Press the Generate button in the header to create your plugin.`,
    },
  },
  lessonFirstProcessor: {
    label: "First Processor",
    config: {
      title: "2. Creating Your First Processor",
      content: `Let's create a simple processor! 

STEP 1: Set Usage
• In Plugin Config, set Usage to "preprocessor" or "postprocessor"

STEP 2: Add Video Input
• Expand Input category
• Drag "Video Input" to canvas

STEP 3: Add a Custom Processor
• Expand Pre-processor or Post-processor category
• Drag "Create New (Beta)" to canvas
• Describe what you want in chat mode, or write code directly

STEP 4: Connect Nodes
• Click the right handle of Video Input
• Drag to the left handle of your processor

STEP 5: Add Output
• Expand Output category
• Drag "Pipeline Output" to canvas
• Connect your processor to it

STEP 6: Generate!
• Click Generate to create your plugin

Congratulations! You've created your first processor!`,
    },
  },
  lessonNodeTypes: {
    label: "Node Types",
    config: {
      title: "3. Understanding Node Types",
      content: `Each node serves a purpose in your pipeline!

INPUT NODES:
• Video Input - Accepts video frames from camera/file
• Text Prompt - Text input with weight for AI models
• Image Input - Reference images for image-to-video
• Parameters - Key-value config for runtime

PIPELINE NODE:
• Fetches AI pipelines from your Scope server
• These are remote inference models
• Toggle code to see the Python implementation

PREPROCESSOR NODES:
• Process input before the main pipeline
• Use Scope server pipelines or create custom with AI

POSTPROCESSOR NODES:
• Process output after the main pipeline  
• Use Scope server pipelines or create custom with AI

OUTPUT NODES:
• Pipeline Output - Main AI result`,
    },
  },
  lessonPreprocessors: {
    label: "Preprocessors",
    config: {
      title: "4. Working with Preprocessors",
      content: `Preprocessors modify input before the main AI pipeline!

WHEN TO USE:
• You need to prepare input for AI models
• Add custom processing logic
• Transform video in specific ways

AVAILABLE OPTIONS:
• Use pipelines from your Scope server
• Create custom with AI - describe what you want in chat mode

CREATING CUSTOM:
• Use "Create New (Beta)" in Pre-processor category
• Write Python code in code mode
• Process frames before main pipeline

TIPS:
• Preprocessors run BEFORE the main pipeline
• Connect output to main pipeline input
• Can chain multiple preprocessors`,
    },
  },
  lessonPostprocessors: {
    label: "Postprocessors",
    config: {
      title: "5. Working with Postprocessors",
      content: `Postprocessors enhance or modify the AI output!

WHEN TO USE:
• After AI generation completes
• Add visual effects or transformations
• Process the final output

AVAILABLE OPTIONS:
• Use pipelines from your Scope server
• Create custom with AI - describe what you want in chat mode

CREATING CUSTOM:
• Use "Create New (Beta)" in Post-processor category
• Write Python code in code mode
• Process output frames

TIPS:
• Postprocessors run AFTER the main pipeline
• Can chain multiple postprocessors
• The order matters for best results`,
    },
  },
};

export function getDefaultWorkflow(): { 
  nodes: Array<{ type: string; position: { x: number; y: number }; config?: Record<string, unknown> }>;
  edges: Array<{ source: number; target: number }>;
} {
  return {
    nodes: [
      // Welcome Note
      {
        type: "noteGuide",
        position: { x: 200, y: 280 },
        config: {
          title: "Welcome to OpenScope! 🎉",
          content: `OpenScope lets you build realtime video pipelines visually.

What's happening now 🚩:
- Video Input → Main Pipeline → Pre-processor → Output
- 3 Style nodes (Chromatic, VHS, Bloom) are adding effects to the video

How to customize 🚩:
1. Select the post-processor to start twerking the setting in the Properties panel
2. Add more Style nodes from the left panel to add more effects
3. Click the clear button in the header to begin a new section

To run 🚀: Click the "Run" button in the top right to start the preview!

Need help? Check the Guides section in the left panel for tutorials.`,
        },
      },
      // Plugin Config
      {
        type: "pluginConfig",
        position: { x: 200, y: 150 },
        config: {
          pipelineId: "bloom",
          pluginName: "Starter",
          pluginDescription: "Starter effects pipeline",
          usage: "postprocessor",
          mode: "video",
          supportsPrompts: false,
        },
      },
      // Video Input
      {
        type: "videoInput",
        position: { x: 600, y: 150 },
        config: {
          videoPreviewUrl: "/sample.mp4",
        },
      },
      // Main Pipeline
      {
        type: "pipeline",
        position: { x: 950, y: 150 },
        config: {
          pipelineId: "",
        },
      },
      // Post-processor
      {
        type: "custom",
        position: { x: 1300, y: 250 },
        config: {
          createNewKind: "postprocessor",
          pythonCode: `"""Postprocessor - Connect Style nodes to add effects."""

from typing import TYPE_CHECKING
import torch
from scope.core.pipelines.interface import Pipeline, Requirements

if TYPE_CHECKING:
    from scope.core.pipelines.base_schema import BasePipelineConfig


class StarterPostConfig:
    pipeline_id = "postprocessor"
    pipeline_name = "Postprocessor"
    pipeline_description = "Connect Style nodes to this processor to add effects"
    pass


class StarterPostPipeline(Pipeline):
    def get_config_class(cls):
        return StarterPostConfig

    def __init__(self, device=None, **kwargs):
        self.device = device or torch.device("cuda" if torch.cuda.is_available() else "cpu")

    def Prepare(self, **kwargs):
        return Requirements(input_size=1)

    def __call__(self, **kwargs):
        video = kwargs.get("video")
        if video is None:
            raise ValueError("Video required")
        
        frames = torch.stack([frame.squeeze(0) for frame in video], dim=0)
        frames = frames.to(device=self.device, dtype=torch.float32) / 255.0
        
        result = frames
        
        return {"video": result.clamp(0, 1).cpu()}


def register_pipelines(register):
    register(StarterPostPipeline)`,
        },
      },
      {
        type: "style_chromatic",
        position: { x: 920, y: 350 },
        config: {
          intensity: 0.3,
          enabled: true,
        },
      },
      // Style 2 - VHS
      {
        type: "style_vhs",
        position: { x: 920, y: 450 },
        config: {
          scanLineIntensity: 0.3,
          noise: 0.1,
          tracking: 0.2,
          enabled: true,
        },
      },
      // Style 3 - Bloom
      {
        type: "style_bloom",
        position: { x: 920, y: 550 },
        config: {
          intensity: 0.5,
          enabled: true,
        },
      },
      // Output
      {
        type: "pipelineOutput",
        position: { x: 1650, y: 150 },
        config: {},
      },
    ],
    edges: [
      // Plugin Config → Video Input
      { source: 1, target: 2 },
      // Video Input → Main Pipeline
      { source: 2, target: 3 },
      // Main Pipeline → Pre-processor
      { source: 3, target: 4 },
      // Pre-processor → Output
      { source: 4, target: 8 },
      // Style 1 → Pre-processor (purple)
      { source: 5, target: 4 },
      // Style 2 → Pre-processor (purple)
      { source: 6, target: 4 },
      // Style 3 → Pre-processor (purple)
      { source: 7, target: 4 },
    ],
  };
}

export const useGraphStore = create<GraphState>((set, get) => ({
  nodes: [],
  edges: [],
  selectedNode: null,

  loadDefaultWorkflow: () => {
    const { nodes: existingNodes, addNodesWithEdges } = get();
    if (existingNodes.length > 0) return;
    
    const defaultWorkflow = getDefaultWorkflow();
    addNodesWithEdges(defaultWorkflow.nodes, defaultWorkflow.edges);
  },

  addNode: (type: string, position: { x: number; y: number }, config?: Record<string, unknown>, options?: { selectNode?: boolean }) => {
    let defaults = nodeDefaults[type] || { label: type, config: {} };
    let labelOverride: string | undefined;
    
    if (type.startsWith("pipeline_")) {
      const pipelineId = type.replace("pipeline_", "");
      const usage = config?.usage as string | undefined;
      
      if (pipelineId === "customPreprocessor") {
        defaults = {
          label: "Preprocessor",
          config: { pipelineId: "my-preprocessor", isCustomPipeline: true, usage: "preprocessor" },
        };
      } else if (pipelineId === "customPostprocessor") {
        defaults = {
          label: "Postprocessor",
          config: { pipelineId: "my-postprocessor", isCustomPipeline: true, usage: "postprocessor" },
        };
      } else {
        let label = "Main Pipeline";
        if (usage === "preprocessor") {
          label = "Preprocessor";
        } else if (usage === "postprocessor") {
          label = "Postprocessor";
        }
        defaults = {
          label,
          config: { pipelineId, usage },
        };
      }
    }

    if ((type === "parameters" || type === "custom") && config?.createNewKind) {
      labelOverride = config.createNewKind === "preprocessor" ? "Preprocessor" : "Postprocessor";
    }
    
    const newNode: Node<NodeData> = {
      id: uuidv4(),
      type: "scopeNode",
      position,
      selected: options?.selectNode !== false,
      data: {
        label: labelOverride || defaults.label || type,
        type,
        config: { ...defaults.config, ...config },
      },
    };
    
    if (options?.selectNode === false) {
      set({ nodes: [...get().nodes, newNode] });
    } else {
      set({ nodes: [...get().nodes, newNode], selectedNode: newNode.id });
    }
  },

  addNodesWithEdges: (nodes, edges) => {
    const NODE_WIDTH = 280;
    const NODE_HEIGHT = 150;
    const HORIZONTAL_GAP = 100;
    const VERTICAL_GAP = 80;

    const needsLayout = nodes.some(n => !n.position || n.position.x < 200);

    const newNodes: Node<NodeData>[] = nodes.map((n, index) => {
      const defaults = nodeDefaults[n.type] || { label: n.type, config: {} };
      
      let position = n.position;
      if (needsLayout && n.position) {
        position = {
          x: 50 + index * (NODE_WIDTH + HORIZONTAL_GAP),
          y: 50 + Math.floor(index / 3) * (NODE_HEIGHT + VERTICAL_GAP),
        };
      }

      let config = { ...defaults.config, ...n.config };
      if (n.type.startsWith("pipeline_")) {
        const pipelineId = n.type.replace("pipeline_", "");
        config = { ...config, pipelineId };
      }

      // Generate pythonCode for nodes that support code mode
      if (!config.pythonCode) {
        const codeTypes = ["pluginConfig", "custom", "pipeline", "pipeline_customPreprocessor", "pipeline_customPostprocessor"];
        const isCodeType = codeTypes.some(t => n.type === t) || n.type.startsWith("pipeline_") || n.type.startsWith("style_");
        if (isCodeType) {
          config.pythonCode = getCodeForNodeType(n.type, config, config.createNewKind as string | undefined);
        }
      }

      // Determine label based on type and createNewKind
      let label = defaults.label || n.type;
      if (n.type === "custom" && config.createNewKind === "preprocessor") {
        label = "Preprocessor";
      } else if (n.type === "custom" && config.createNewKind === "postprocessor") {
        label = "Postprocessor";
      }

      return {
        id: uuidv4(),
        type: "scopeNode",
        position,
        selected: false,
        data: {
          label,
          type: n.type,
          config,
        },
      };
    });

    let newEdges: Edge[] = [];
    
    const isInputNode = (type: string) => 
      ["videoInput", "textPrompt", "imageInput", "parameters"].includes(type);
    const isOutputNode = (type: string) => 
      type === "pipelineOutput";
    const isPipelineNode = (type: string) => 
      type.startsWith("pipeline_") || type === "pipeline";
    
    if (edges && edges.length > 0) {
      newEdges = edges.map((e) => {
        const sourceNode = newNodes[e.source];
        const targetNode = newNodes[e.target];
        const isStyleToProcessor = sourceNode?.data.type.startsWith("style_") && 
          (targetNode?.data.type === "custom" || targetNode?.data.type.startsWith("pipeline_"));
        
        return {
          id: uuidv4(),
          source: sourceNode?.id,
          target: targetNode?.id,
          sourceHandle: isStyleToProcessor ? "styles" : undefined,
          targetHandle: isStyleToProcessor ? "styles" : undefined,
          type: "smoothstep",
          animated: true,
          style: isStyleToProcessor ? { stroke: "#a855f7", strokeWidth: 2 } : { stroke: "hsl(var(--primary))", strokeWidth: 2 },
        };
      });
    } else if (newNodes.length > 1) {
      const pluginConfig = newNodes.find(n => n.data.type === "pluginConfig");
      const inputNodes = newNodes.filter(n => isInputNode(n.data.type));
      const pipelineNodes = newNodes.filter(n => isPipelineNode(n.data.type));
      const outputNodes = newNodes.filter(n => isOutputNode(n.data.type));

      let colIndex = 0;
      
      if (pluginConfig) {
        pluginConfig.position = { x: 50, y: 50 + colIndex * (NODE_HEIGHT + VERTICAL_GAP) };
        colIndex++;
      }

      inputNodes.forEach(node => {
        node.position = { x: 50 + (NODE_WIDTH + HORIZONTAL_GAP), y: 50 + colIndex * (NODE_HEIGHT + VERTICAL_GAP) };
        if (pluginConfig) {
          newEdges.push({
            id: uuidv4(),
            source: pluginConfig.id,
            target: node.id,
            type: "smoothstep",
            animated: true,
          });
        }
        colIndex++;
      });

      pipelineNodes.forEach(node => {
        node.position = { x: 50 + 2 * (NODE_WIDTH + HORIZONTAL_GAP), y: 50 + colIndex * (NODE_HEIGHT + VERTICAL_GAP) };
        const firstInput = inputNodes[0] || pluginConfig;
        if (firstInput) {
          newEdges.push({
            id: uuidv4(),
            source: firstInput.id,
            target: node.id,
            type: "smoothstep",
            animated: true,
          });
        }
        colIndex++;
      });

      outputNodes.forEach(node => {
        node.position = { x: 50 + 3 * (NODE_WIDTH + HORIZONTAL_GAP), y: 50 };
        pipelineNodes.forEach(pipeline => {
          newEdges.push({
            id: uuidv4(),
            source: pipeline.id,
            target: node.id,
            type: "smoothstep",
            animated: true,
          });
        });
      });
    }

    const pluginConfigNode = newNodes.find(n => n.data.type === "pluginConfig");

    set({
      nodes: [...get().nodes, ...newNodes],
      edges: [...get().edges, ...newEdges],
      selectedNode: null,
    });
  },

  updateNodeConfig: (nodeId: string, config: Record<string, unknown>) => {
    set({
      nodes: get().nodes.map((node) =>
        node.id === nodeId
          ? { ...node, data: { ...node.data, config: { ...node.data.config, ...config } } }
          : node
      ),
    });
  },

  updateNodeType: (nodeId: string, type: string, config?: Record<string, unknown>) => {
    set({
      nodes: get().nodes.map((node) => {
        if (node.id !== nodeId) return node;
        const defaults = nodeDefaults[type] || { label: type, config: {} };
        return {
          ...node,
          data: {
            ...node.data,
            type,
            label: defaults.label || type,
            config: { ...(defaults.config || {}), ...(config || {}) },
          },
        };
      }),
    });
  },

  deleteNode: (nodeId: string) => {
    set({
      nodes: get().nodes.filter((node) => node.id !== nodeId),
      edges: get().edges.filter(
        (edge) => edge.source !== nodeId && edge.target !== nodeId
      ),
      selectedNode: get().selectedNode === nodeId ? null : get().selectedNode,
    });
  },

  selectNode: (nodeId: string | null) => {
    set({ selectedNode: nodeId });
  },

  clearAll: () => {
    set({ nodes: [], edges: [], selectedNode: null });
  },

  addOutputNode: () => {
    const { nodes, edges } = get();
    if (nodes.length === 0) return;

    const pluginConfig = nodes.find(n => n.data.type === "pluginConfig");
    const usage = (pluginConfig?.data?.config?.usage as string) || "main";

    let outputType = "pipelineOutput";

    let rightmostNode = nodes[0];
    let maxX = nodes[0].position.x;
    for (const node of nodes) {
      if (node.position.x > maxX) {
        maxX = node.position.x;
        rightmostNode = node;
      }
    }

    const outputDefaults = nodeDefaults[outputType] || { label: outputType, config: {} };
    const outputNode: Node<NodeData> = {
      id: uuidv4(),
      type: "scopeNode",
      position: { x: maxX + 200, y: rightmostNode.position.y },
      selected: true,
      data: {
        label: outputDefaults.label || outputType,
        type: outputType,
        config: outputDefaults.config || {},
      },
    };

    const newEdge: Edge = {
      id: uuidv4(),
      source: rightmostNode.id,
      target: outputNode.id,
      type: "smoothstep",
      animated: true,
    };

    set({
      nodes: [...nodes, outputNode],
      edges: [...edges, newEdge],
      selectedNode: outputNode.id,
    });
  },

  onNodesChange: (changes) => {
    set({ nodes: applyNodeChanges(changes, get().nodes) });
  },

  onEdgesChange: (changes) => {
    set({ edges: applyEdgeChanges(changes, get().edges) });
  },

  onConnect: (connection: Connection) => {
    set({ edges: addEdge({ ...connection, id: uuidv4() }, get().edges) });
  },

  addEdge: (edge: Edge) => {
    set({ edges: addEdge(edge, get().edges) });
  },
}));
