"""Templates router for plugin templates."""

from typing import List, Optional
from pydantic import BaseModel

from fastapi import APIRouter, HTTPException

router = APIRouter()


class Template(BaseModel):
    """Plugin template."""

    id: str
    name: str
    description: str
    category: str
    nodes: list
    edges: Optional[list] = None
    icon: Optional[str] = None
    github_url: Optional[str] = None


# Built-in starter templates - 6 total per mvp-phase.md
STARTER_TEMPLATES = [
    {
        "id": "blank",
        "name": "Blank Plugin",
        "description": "Start from scratch - add your own pre/post processors",
        "category": "Starter",
        "icon": "📄",
        "nodes": [
            {
                "type": "pluginConfig",
                "position": {"x": 50, "y": 50},
                "config": {
                    "pipelineId": "passthrough",
                    "pluginName": "My Plugin",
                    "pluginDescription": "Generated by OpenScope",
                    "usage": "main",
                    "mode": "video",
                    "supportsPrompts": True,
                    "remoteInference": False,
                },
            },
            {"type": "videoInput", "position": {"x": 330, "y": 50}},
            {
                "type": "pipeline",
                "position": {"x": 610, "y": 50},
                "config": {"pipelineId": "passthrough"},
            },
            {"type": "pipelineOutput", "position": {"x": 890, "y": 50}},
        ],
        "edges": [
            {"source": 0, "target": 1},
            {"source": 1, "target": 2},
            {"source": 2, "target": 3},
        ],
    },
    # Templates with processor as main pipeline
    {
        "id": "kaleidoscope-pre",
        "name": "Kaleidoscope",
        "description": "GPU kaleidoscope/mirror effect - 2x/4x, N-fold symmetry, rotation, zoom, warp",
        "category": "Preprocessor",
        "icon": "🔮",
        "nodes": [
            {
                "type": "pluginConfig",
                "position": {"x": 50, "y": 50},
                "config": {
                    "pipelineId": "kaleido-scope",
                    "pluginName": "Kaleido Scope",
                    "pluginDescription": "GPU kaleidoscope/mirror effect",
                    "usage": "main",
                    "mode": "video",
                    "supportsPrompts": True,
                    "remoteInference": False,
                },
            },
            {"type": "videoInput", "position": {"x": 330, "y": 50}},
            {
                "type": "pipeline",
                "position": {"x": 610, "y": 50},
                "config": {
                    "pipelineId": "kaleido-scope",
                    "enabled": True,
                    "mix": 1.0,
                    "mirrorMode": "none",
                    "rotationalEnabled": True,
                    "rotationalSlices": 6,
                    "rotationDeg": 0.0,
                    "zoom": 1.0,
                    "warp": 0.0,
                },
            },
            {"type": "pipelineOutput", "position": {"x": 890, "y": 50}},
        ],
        "edges": [
            {"source": 0, "target": 1},
            {"source": 1, "target": 2},
            {"source": 2, "target": 3},
        ],
    },
    {
        "id": "yolo-mask-pre",
        "name": "YOLO Mask",
        "description": "YOLO26 segmentation - detect and mask objects for VACE inpainting/conditioning",
        "category": "Preprocessor",
        "icon": "✂️",
        "nodes": [
            {
                "type": "pluginConfig",
                "position": {"x": 50, "y": 50},
                "config": {
                    "pipelineId": "yolo_mask",
                    "pluginName": "YOLO Mask",
                    "pluginDescription": "YOLO26 segmentation for VACE inpainting",
                    "usage": "main",
                    "mode": "video",
                    "supportsPrompts": True,
                    "remoteInference": False,
                },
            },
            {"type": "videoInput", "position": {"x": 330, "y": 50}},
            {
                "type": "pipeline",
                "position": {"x": 610, "y": 50},
                "config": {
                    "pipelineId": "yolo_mask",
                    "modelSize": "nano",
                    "outputMode": "mask",
                    "targetClass": "person",
                    "confidenceThreshold": 0.5,
                    "invertMask": False,
                },
            },
            {"type": "pipelineOutput", "position": {"x": 890, "y": 50}},
        ],
        "edges": [
            {"source": 0, "target": 1},
            {"source": 1, "target": 2},
            {"source": 2, "target": 3},
        ],
    },
    # Post-processor templates
    {
        "id": "bloom-post",
        "name": "Bloom Postprocessor",
        "description": "Bloom/glow effect - adds soft light around bright areas",
        "category": "Postprocessor",
        "icon": "✨",
        "nodes": [
            {
                "type": "pluginConfig",
                "position": {"x": 50, "y": 50},
                "config": {
                    "pipelineId": "bloom",
                    "pluginName": "Bloom",
                    "pluginDescription": "Bloom/glow effect",
                    "usage": "main",
                    "mode": "video",
                    "supportsPrompts": True,
                    "remoteInference": False,
                },
            },
            {"type": "videoInput", "position": {"x": 330, "y": 50}},
            {
                "type": "pipeline",
                "position": {"x": 610, "y": 50},
                "config": {
                    "pipelineId": "bloom",
                    "threshold": 0.8,
                    "softKnee": 0.5,
                    "intensity": 1.0,
                    "radius": 8,
                    "downsample": 1,
                    "debug": False,
                },
            },
            {"type": "pipelineOutput", "position": {"x": 890, "y": 50}},
        ],
        "edges": [
            {"source": 0, "target": 1},
            {"source": 1, "target": 2},
            {"source": 2, "target": 3},
        ],
    },
    {
        "id": "cosmic-vfx-post",
        "name": "Cosmic VFX Postprocessor",
        "description": "Real-time VFX: Glitch, Retro, Distortion, Color, Blend, Edge, Blur, and more",
        "category": "Postprocessor",
        "icon": "🚀",
        "nodes": [
            {
                "type": "pluginConfig",
                "position": {"x": 50, "y": 50},
                "config": {
                    "pipelineId": "cosmic-vfx",
                    "pluginName": "Cosmic VFX",
                    "pluginDescription": "30+ visual effects",
                    "usage": "main",
                    "mode": "video",
                    "supportsPrompts": True,
                    "remoteInference": False,
                },
            },
            {"type": "videoInput", "position": {"x": 330, "y": 50}},
            {
                "type": "pipeline",
                "position": {"x": 610, "y": 50},
                "config": {
                    "pipelineId": "cosmic-vfx",
                    "enableGlitch": False,
                    "glitchShader": "basic",
                    "glitchIntensity": 1.0,
                    "enableRetro": False,
                    "retroShader": "vhs",
                    "retroIntensity": 1.0,
                    "enableDistortion": False,
                    "distortionShader": "wave",
                    "distortionIntensity": 1.0,
                    "enableColor": False,
                    "colorShader": "hueshift",
                    "colorIntensity": 1.0,
                    "enableEdge": False,
                    "edgeShader": "sobel",
                    "edgeIntensity": 1.0,
                    "enableBlur": False,
                    "blurShader": "gaussian",
                    "blurIntensity": 1.0,
                    "intensity": 1.0,
                    "speed": 1.0,
                    "hueShift": 0.0,
                    "saturation": 1.0,
                    "brightness": 1.0,
                    "blendMode": "normal",
                },
            },
            {"type": "pipelineOutput", "position": {"x": 890, "y": 50}},
        ],
        "edges": [
            {"source": 0, "target": 1},
            {"source": 1, "target": 2},
            {"source": 2, "target": 3},
        ],
    },
    {
        "id": "vfx-pack-post",
        "name": "VFX Pack Postprocessor",
        "description": "GPU-accelerated VFX: chromatic aberration, VHS/retro CRT, halftone",
        "category": "Postprocessor",
        "icon": "🎬",
        "nodes": [
            {
                "type": "pluginConfig",
                "position": {"x": 50, "y": 50},
                "config": {
                    "pipelineId": "vfx-pack",
                    "pluginName": "VFX Pack",
                    "pluginDescription": "Chromatic, VHS, Halftone effects",
                    "usage": "main",
                    "mode": "video",
                    "supportsPrompts": True,
                    "remoteInference": False,
                },
            },
            {"type": "videoInput", "position": {"x": 330, "y": 50}},
            {
                "type": "pipeline",
                "position": {"x": 610, "y": 50},
                "config": {
                    "pipelineId": "vfx-pack",
                    "chromaticEnabled": True,
                    "chromaticIntensity": 0.3,
                    "chromaticAngle": 0.0,
                    "vhsEnabled": False,
                    "scanLineIntensity": 0.3,
                    "scanLineCount": 100,
                    "vhsNoise": 0.1,
                    "trackingDistortion": 0.2,
                    "halftoneEnabled": False,
                    "halftoneDotSize": 8,
                    "halftoneSharpness": 0.7,
                },
            },
            {"type": "pipelineOutput", "position": {"x": 890, "y": 50}},
        ],
        "edges": [
            {"source": 0, "target": 1},
            {"source": 1, "target": 2},
            {"source": 2, "target": 3},
        ],
    },
]


@router.get("/", response_model=List[dict])
async def list_templates(category: Optional[str] = None):
    """List all available templates."""
    if category:
        return [t for t in STARTER_TEMPLATES if t.get("category") == category]
    return STARTER_TEMPLATES


@router.get("/categories")
async def list_categories():
    """List all template categories."""
    categories = set(t.get("category", "Other") for t in STARTER_TEMPLATES)
    return sorted(list(categories))


@router.get("/{template_id}", response_model=dict)
async def get_template(template_id: str):
    """Get a specific template by ID."""
    for template in STARTER_TEMPLATES:
        if template["id"] == template_id:
            return template
    raise HTTPException(status_code=404, detail="Template not found")
