"""Templates router for plugin templates."""

from typing import List, Optional
from pydantic import BaseModel

from fastapi import APIRouter, HTTPException

router = APIRouter()


class Template(BaseModel):
    """Plugin template."""

    id: str
    name: str
    description: str
    category: str
    nodes: list
    edges: Optional[list] = None
    icon: Optional[str] = None
    github_url: Optional[str] = None


# Built-in starter templates
STARTER_TEMPLATES = [
    {
        "id": "blank",
        "name": "Blank Plugin",
        "description": "Start from scratch with a minimal plugin structure",
        "category": "Starter",
        "icon": "📄",
        "nodes": [
            {
                "type": "pluginConfig",
                "position": {"x": 50, "y": 50},
                "config": {
                    "pipelineId": "my-plugin",
                    "pipelineName": "My Plugin",
                    "pipelineDescription": "Generated by OpenScope",
                    "usage": "main",
                    "mode": "video",
                    "supportsPrompts": True,
                },
            },
            {"type": "videoInput", "position": {"x": 100, "y": 200}},
            {"type": "pipelineOutput", "position": {"x": 400, "y": 200}},
        ],
        "edges": [{"source": 1, "target": 2}],
    },
    # Community Plugin Templates (from actual plugins)
    {
        "id": "kaleido-scope",
        "name": "Kaleido Scope",
        "description": "GPU-accelerated kaleidoscope / mirror effect plugin for Daydream Scope",
        "category": "Community",
        "icon": "🔮",
        "github_url": "https://github.com/daydreamlive/kaleido-scope",
        "nodes": [
            {
                "type": "pluginConfig",
                "position": {"x": 50, "y": 50},
                "config": {
                    "pipelineId": "kaleido-scope",
                    "pipelineName": "Kaleido Scope",
                    "pipelineDescription": "GPU-accelerated kaleidoscope / mirror effect plugin for Daydream Scope",
                    "usage": "postprocessor",
                    "mode": "video",
                    "supportsPrompts": False,
                },
            },
            {"type": "videoInput", "position": {"x": 100, "y": 200}},
            {
                "type": "kaleido",
                "position": {"x": 300, "y": 200},
                "config": {"slices": 6, "rotation": 0, "zoom": 1},
            },
            {"type": "postprocessorOutput", "position": {"x": 500, "y": 200}},
        ],
        "edges": [
            {"source": 1, "target": 2},
            {"source": 2, "target": 3},
        ],
    },
    {
        "id": "scope-yolo-mask",
        "name": "YOLO Mask",
        "description": "YOLO26 person segmentation preprocessor for Daydream Scope",
        "category": "Community",
        "icon": "✂️",
        "github_url": "https://github.com/daydreamlive/scope-yolo-mask",
        "nodes": [
            {
                "type": "pluginConfig",
                "position": {"x": 50, "y": 50},
                "config": {
                    "pipelineId": "scope-yolo-mask",
                    "pipelineName": "YOLO Mask",
                    "pipelineDescription": "YOLO26 person segmentation preprocessor for Daydream Scope",
                    "usage": "preprocessor",
                    "mode": "video",
                    "supportsPrompts": False, 
                },
            },
            {"type": "videoInput", "position": {"x": 100, "y": 200}},
            {
                "type": "segmentation",
                "position": {"x": 300, "y": 200},
                "config": {"model": "yolo", "targetClass": "person", "confidence": 0.5},
            },
            {"type": "preprocessorOutput", "position": {"x": 500, "y": 200}},
        ],
        "edges": [
            {"source": 1, "target": 2},
            {"source": 2, "target": 3},
        ],
    },
    {
        "id": "scope-cinematic",
        "name": "Cinematic",
        "description": "Cinematic post-processor for Scope - transforms videos into cinematic masterpieces",
        "category": "Community",
        "icon": "🎬",
        "github_url": "https://github.com/daydreamlive/scope-cinematic",
        "nodes": [
            {
                "type": "pluginConfig",
                "position": {"x": 50, "y": 50},
                "config": {
                    "pipelineId": "scope-cinematic",
                    "pipelineName": "Cinematic",
                    "pipelineDescription": "Cinematic post-processor for Scope - transforms videos into cinematic masterpieces",
                    "usage": "postprocessor",
                    "mode": "video",
                    "supportsPrompts": False,
                },
            },
            {"type": "videoInput", "position": {"x": 100, "y": 200}},
            {
                "type": "colorGrading",
                "position": {"x": 300, "y": 150},
                "config": {
                    "temperature": 10,
                    "tint": 0,
                    "saturation": 10,
                    "contrast": 15,
                },
            },
            {
                "type": "vignette",
                "position": {"x": 300, "y": 280},
                "config": {"intensity": 0.4, "smoothness": 0.5},
            },
            {"type": "postprocessorOutput", "position": {"x": 500, "y": 200}},
        ],
        "edges": [
            {"source": 1, "target": 2},
            {"source": 2, "target": 3},
            {"source": 2, "target": 4},
            {"source": 3, "target": 5},
            {"source": 4, "target": 5},
        ],
    },
    {
        "id": "scope-agent",
        "name": "Scope Agent",
        "description": "AI Agent control for Daydream Scope - control Scope via WebSocket",
        "category": "Community",
        "icon": "🤖",
        "github_url": "https://github.com/daydreamlive/scope-agent",
        "nodes": [
            {
                "type": "pluginConfig",
                "position": {"x": 50, "y": 50},
                "config": {
                    "pipelineId": "scope-agent",
                    "pipelineName": "Scope Agent",
                    "pipelineDescription": "AI Agent control for Daydream Scope - control Scope via WebSocket",
                    "usage": "main",
                    "mode": "video",
                    "supportsPrompts": True,
                },
            },
            {"type": "videoInput", "position": {"x": 100, "y": 200}},
            {"type": "textPrompt", "position": {"x": 100, "y": 350}},
            {"type": "pipelineOutput", "position": {"x": 400, "y": 200}},
        ],
        "edges": [
            {"source": 1, "target": 3},
            {"source": 2, "target": 3},
        ],
    },
    {
        "id": "scope-audio-transcription",
        "name": "Audio Transcription",
        "description": "Real-time audio transcription plugin - voice-controlled AI video generation",
        "category": "Community",
        "icon": "🎤",
        "github_url": "https://github.com/kfaist/scope-audio-transcription",
        "nodes": [
            {
                "type": "pluginConfig",
                "position": {"x": 50, "y": 50},
                "config": {
                    "pipelineId": "scope-audio-transcription",
                    "pipelineName": "Audio Transcription",
                    "pipelineDescription": "Real-time audio transcription plugin for Daydream Scope - voice-controlled AI video generation",
                    "usage": "main",
                    "mode": "video",
                    "supportsPrompts": True,
                },
            },
            {"type": "videoInput", "position": {"x": 100, "y": 200}},
            {"type": "textPrompt", "position": {"x": 100, "y": 350}},
            {"type": "pipelineOutput", "position": {"x": 400, "y": 200}},
        ],
        "edges": [
            {"source": 1, "target": 3},
            {"source": 2, "target": 3},
        ],
    },
]


@router.get("/", response_model=List[dict])
async def list_templates(category: Optional[str] = None):
    """List all available templates."""
    if category:
        return [t for t in STARTER_TEMPLATES if t.get("category") == category]
    return STARTER_TEMPLATES


@router.get("/categories")
async def list_categories():
    """List all template categories."""
    categories = set(t.get("category", "Other") for t in STARTER_TEMPLATES)
    return sorted(list(categories))


@router.get("/{template_id}", response_model=dict)
async def get_template(template_id: str):
    """Get a specific template by ID."""
    for template in STARTER_TEMPLATES:
        if template["id"] == template_id:
            return template
    raise HTTPException(status_code=404, detail="Template not found")
